from typing import Any, Dict, List, TypedDict, Annotated

from langchain_core.messages import AIMessage, BaseMessage

try:
    from langgraph.graph import END, START, StateGraph
    from langgraph.graph.message import add_messages
except Exception:  # pragma: no cover - optional runtime fallback
    END = None
    START = None
    StateGraph = None
    add_messages = None


if add_messages is not None:
    class LLMGraphState(TypedDict):
        messages: Annotated[List[BaseMessage], add_messages]
else:
    class LLMGraphState(TypedDict):
        messages: List[BaseMessage]


def invoke_model_with_graph(
    client: Any,
    messages: List[BaseMessage],
    recursion_limit: int = 6,
) -> AIMessage:
    if StateGraph is None or START is None or END is None:
        # Defensive fallback if LangGraph is unavailable at runtime.
        return client.invoke(messages)

    def _assistant_node(state: LLMGraphState) -> Dict[str, List[BaseMessage]]:
        return {"messages": [client.invoke(state["messages"])]}

    graph = StateGraph(LLMGraphState)
    graph.add_node("assistant", _assistant_node)
    graph.add_edge(START, "assistant")
    graph.add_edge("assistant", END)
    app = graph.compile()

    final_state = app.invoke(
        {"messages": messages},
        config={"recursion_limit": max(2, recursion_limit)},
    )
    for message in reversed(final_state.get("messages") or []):
        if isinstance(message, AIMessage):
            return message

    raise RuntimeError("No AI response generated by graph execution.")
