from typing import Dict, List, Literal, Optional, Tuple

from pydantic import BaseModel, Field


class ChatCompletionsRequest(BaseModel):
    """Request body for the /chat/completions endpoint."""

    messages: List[Dict[str, str]] = Field(
        description="A list of messages comprising the conversation so far. "
    )
    model: str = Field(description="ID of the model to use.")
    frequency_penalty: Optional[float | None] = Field(
        0,
        description="Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim.",
        ge=-2.0,
        le=2.0,
    )
    logit_bias: Optional[Dict[int, int] | None] = Field(
        None,
        description="Modify the likelihood of specified tokens appearing in the completion. Accepts a JSON object that maps tokens (specified by their token ID in the tokenizer) to an associated bias value from -100 to 100. Mathematically, the bias is added to the logits generated by the model prior to sampling. The exact effect will vary per model, but values between -1 and 1 should decrease or increase likelihood of selection; values like -100 or 100 should result in a ban or exclusive selection of the relevant token.",
    )
    max_tokens: Optional[int | None] = Field(
        None,
        description="The maximum number of tokens to generate in the chat completion. The total length of input tokens and generated tokens is limited by the model's context length.",
        ge=1,
    )
    presence_penalty: Optional[float | None] = Field(
        0,
        description="Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics.",
        ge=-2.0,
        le=2.0,
    )
    stop: Optional[str | List[str] | None] = Field(
        None,
        description="Up to 4 sequences where the API will stop generating further tokens.",
    )
    temperature: Optional[float | None] = Field(
        1,
        description="What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. We generally recommend altering this or `top_p` but not both.",
        ge=0,
        le=2,
    )
    top_p: Optional[float | None] = Field(
        1,
        description="An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered. We generally recommend altering this or `temperature` but not both.",
        ge=0,
        le=1,
    )
    user: Optional[str] = Field(
        None,
        description="A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.",
    )
    function_call: Optional[str | Dict] = Field(
        None,
        description='Deprecated in favor of `tool_choice`. Controls which (if any) function is called by the model. `none` means the model will not call a function and instead generates a message. `auto` means the model can pick between generating a message or calling a function. Specifying a particular function via `{"name": "my_function"}` forces the model to call that function. `none` is the default when no functions are present. `auto` is the default if functions are present.',
    )
    functions: Optional[List[Dict]] = Field(
        None,
        description="Deprecated in favor of `tools`. A list of functions the model may generate JSON inputs for.",
    )
    additional_kwargs: Optional[Dict] = Field(
        {}, description="Additional kwargs to log."
    )
    userID: Optional[str] = Field(
        "",
        description="A unique identifier representing your end-user, used for logging and monitoring in LLMOPs.",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a helpful assistant.",
                    },
                    {
                        "role": "user",
                        "content": "Hello, how are you?",
                    },
                ],
                "model": "",
            }
        }


class EmbeddingsRequest(BaseModel):
    """Request body for the /embeddings endpoint."""

    input: str | List[str] = Field(
        description="Input text to embed, encoded as a string or array of tokens. To embed multiple inputs in a single request, pass an array of strings or array of token arrays. The input must not exceed the max input tokens for the model (8192 tokens for `text-embedding-ada-002`) and cannot be an empty string.",
    )
    model: str = Field(description="ID of the model to use.")
    encoding_format: Optional[Literal["float", "base64"]] = Field(
        "float",
        description="The format to return the embeddings in. Can be either float or base64.",
    )
    user: Optional[str] = Field(
        "",
        description="A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.",
    )
    additional_kwargs: Optional[Dict] = Field(
        {}, description="Additional kwargs to log."
    )

    class Config:
        json_schema_extra = {
            "example": {
                "input": "Hello world!",
                "model": "",
            }
        }


class VectorQueryRequest(BaseModel):
    """Request body for the /vector-store/query endpoint."""

    vector: List[float] | None = Field(
        None,
        description="The query vector. This should be the same length as the dimension of the index being queried. Each `query()` request can contain only one of the parameters `id` or `vector`.",
    )
    id: str | None = Field(
        None,
        description="The unique ID of the vector to be used as a query vector. Each `query()` request can contain only one of the parameters `queries`, `vector`, or `id`.",
        max_length=512,
    )
    queries: List[Dict] | List[Tuple] | None = Field(
        None,
        description="DEPRECATED. The query vectors. Each `query()` request can contain only one of the parameters `queries`, `vector`, or `id`.",
    )
    top_k: int | None = Field(
        description="The number of results to return for each query.",
        le=10000,
        ge=1,
    )
    namespace: str | None = Field(None, description="The namespace to query.")
    filter: Dict[str, str | float | int | bool | List | dict] | None = Field(
        None,
        description="The filter to apply. You can use vector metadata to limit your search.",
    )
    include_values: bool | None = Field(
        None,
        description="Indicates whether vector values are included in the response.",
    )
    include_metadata: bool | None = Field(
        None,
        description="Indicates whether metadata is included in the response as well as the ids.",
    )
    sparse_vector: Dict[str, List[float] | List[int]] | None = Field(
        None,
        description="Vector sparse data. Represented as a list of indices and a list of corresponded values, which must be the same length.",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "id": "Fine-tuning large neural language models_1",
                "top_k": 5,
                "include_metadata": True,
            }
        }


class SparseValues(BaseModel):
    """Vector sparse data. Represented as a list of indices and a list of corresponded values, which must be the same length."""

    indices: List[int] = Field(description="The indices of the sparse data.")
    values: List[float] = Field(
        description="The corresponding values of the sparse data, which must be the same length as the indices."
    )


class Vector(BaseModel):
    """Vector data."""

    id: str = Field(
        description="This is the vector's unique id.", max_length=512, min_length=1
    )
    values: List[float] = Field(
        description="This is the vector data included in the request."
    )
    sparse_values: SparseValues | None = Field(
        None,
        description="Vector sparse data. Represented as a list of indices and a list of corresponded values, which must be the same length.",
    )
    metadata: Dict | None = Field(
        None, description="This is the metadata included in the request."
    )


class VectorUpsertRequest(BaseModel):
    """Request body for the /vector-store/upsert endpoint."""

    vectors: List[tuple] | List[Dict] | List[Vector] = Field(
        description="An array containing the vectors to upsert. Recommended batch limit is 100 vectors."
    )
    namespace: str | None = Field(
        None,
        description="This is the namespace name where you upsert vectors. Not supported by projects on the gcp-starter environment.",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "vectors": [
                    {
                        "id": "test",
                        "values": [0.1] * 1536,
                    }
                ],
                "namespace": "test-namespace",
            }
        }


class VectorDeleteRequest(BaseModel):
    """Request body for the /vector-store/delete endpoint."""

    ids: List[str] | None = Field(None, description="Vectors to delete.")
    delete_all: bool | None = Field(
        None,
        description="This indicates that all vectors in the namespace should be deleted. Not supported by projects on the gcp-starter environment.",
    )
    namespace: str | None = Field(
        None, description="The namespace to delete vectors from, if applicable."
    )
    filter: Dict[str, str | float | int | bool | List | dict] | None = Field(
        None,
        description="If specified, the metadata filter here will be used to select the vectors to delete. This is mutually exclusive with specifying IDs to delete in the ids param or using delete_all=True. See https://www.pinecone.io/docs/metadata-filtering/. Not supported by projects on the gcp-starter environment.",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "ids": ["test"],
                "namespace": "test-namespace",
            }
        }


class CreateChatbotRequest(BaseModel):
    """Request body for the /chatbot/create endpoint."""

    name: str = Field(description="Name of the chatbot.")
    model: str = Field(description="Name of the model to use.")
    description: str | None = Field(
        None,
        description="Description of the chatbot. This is used as the system message when the chatbot is first created.",
    )
    cache: bool = Field(True, description="Whether to use cache for the chatbot.")
    cache_probability: float = Field(
        0.5,
        description="Probability of using cache (only if cache is enabled).",
        ge=0,
        le=1,
    )
    has_knowledgebase: bool = Field(
        False, description="Whether to connect a knowledgebase to the chatbot."
    )
    knowledgebase_id: str | None = Field(None, description="ID of the knowledgebase.")
    chunks_to_retrieve: int = Field(
        5, description="Number of chunks to retrieve from the knowledgebase."
    )
    created_by: str = Field(
        description="ID of the user who created the chatbot (recommended to be the email). *NOTE: If intending to use knowledgebases, this must be the email of the user who has access to the knowledgebase.*"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "name": "test",
                "model": "<MODEL NAME>",
                "description": "You are a helpful assistant",
                "cache": True,
                "cache_probability": 1.0,
                "has_knowledgebase": False,
                "knowledgebase_id": "<KNOWLEDGEBASE ID>",
                "chunks_to_retrieve": 5,
                "created_by": "<EMAIL>",
            }
        }


class PatchChatbotRequest(BaseModel):
    """Request body for the PATCH /chatbot/{chatbot_id} endpoint."""

    name: str | None = Field(
        None,
        description="Name of the chatbot. If not specified, the chatbot will keep its current name.",
    )
    model: str | None = Field(
        None,
        description="Name of the model to use. If not specified, the chatbot will keep its current model.",
    )
    description: str | None = Field(
        None,
        description="Description of the chatbot. This is used as the system message when the chatbot is first created. If not specified, the chatbot will keep its current description.",
    )
    cache: bool | None = Field(
        None,
        description="Whether to use cache for the chatbot. If not specified, the chatbot will keep its current cache setting.",
    )
    cache_probability: float | None = Field(
        None,
        description="Probability of using cache (only if cache is enabled). If not specified, the chatbot will keep its current cache probability.",
        ge=0,
        le=1,
    )
    has_knowledgebase: bool | None = Field(
        None,
        description="Whether to connect a knowledgebase to the chatbot. If not specified, the chatbot will keep its current knowledgebase setting.",
    )
    knowledgebase_id: str | None = Field(
        None,
        description="ID of the knowledgebase. If not specified, the chatbot will keep its current knowledgebase.",
    )
    chunks_to_retrieve: int | None = Field(
        None,
        description="Number of chunks to retrieve from the knowledgebase. If not specified, the chatbot will keep its current chunks to retrieve.",
    )
    created_by: str | None = Field(
        None,
        description="ID of the user who created the chatbot (recommended to be the email). *NOTE: If intending to use knowledgebases, this must be the email of the user who has access to the knowledgebase.* If not specified, the chatbot will keep its current creator.",
    )

    class Config:
        json_schema_extra = {
            "example": {
                "name": "test-again",
                "description": "You are a helpful bot",
            }
        }


class ChatbotChatRequest(BaseModel):
    """Request body for the /chatbot/{chatbot_id}/chat endpoint."""

    message: str = Field(description="Message to send to the chatbot.")

    class Config:
        json_schema_extra = {
            "example": {
                "message": "Hello, how are you?",
            }
        }


class Message(BaseModel):
    """
    # Message
    Model class to represent a message

    ## Attributes
    - `role` (Literal["system", "user", "assistant", "function"]): the role of the message
    - `content` (str): the content of the message
    """

    role: Literal["system", "user", "assistant", "function"]
    """The role of the message"""
    content: str
    """The content of the message"""


class UtilsVector(BaseModel):
    """
    # Vector
    A model class for a vector object.

    ## Attributes
    - `embeddings` (List[float]): A list of floating point numbers representing the vector.

    ## Optional Attributes
    - `id` (str): A unique identifier for the vector. Defaults to "".
    - `metadata` (Dict): Optional dictionary of metadata for the vector. Defaults to {}.
    """

    embeddings: List[float]
    """A list of floating point numbers representing the vector."""

    id: Optional[str] = ""
    """A unique identifier for the vector."""
    metadata: Optional[Dict] = {}
    """Optional dictionary of metadata for the vector."""


class Usage(BaseModel):
    """
    # Usage
    Defines Usage class with the following attributes:

    ## Attributes
    - `prompt_tokens` (int): an integer representing the number of tokens in the prompt
    - `completion_tokens` (int): an integer representing the number of tokens in the completion
    - `total_tokens` (int): an integer representing the total number of tokens in the Usage
    """

    prompt_tokens: int = 0
    """The number of tokens in the prompt"""
    completion_tokens: int = 0
    """The number of tokens in the completion"""
    total_tokens: int = 0
    """The total number of tokens in the Usage"""


class Response(BaseModel):
    """
    # Response
    Represents the response from an inference API.

    ## Attributes
    - `message` (Message): Message object that the API generated as a response.
    - `created` (int): Unix timestamp for when the response was created.
    - `latency` (int): Time in milliseconds taken to generate the response.
    - `from_cache` (bool): Whether the response was served from cache or not.

    ## Optional Attributes
    - `model` (str): String representation of the model used to generate the response. Defaults to "".
    - `usage` (Usage): Usage object containing metrics of resource usage from generating the response. Defaults to Usage().
    - `additional_kwargs` (Dict): Optional dictionary of additional keyword arguments. Defaults to {}.
    """

    message: Message
    """Message object that the API generated as a response"""
    created: int
    """Unix timestamp for when the response was created"""
    latency: int
    """Time in milliseconds taken to generate the response"""
    from_cache: bool
    """Whether the response was served from cache or not"""

    model: Optional[str] = ""
    """String representation of the model used to generate the response"""
    usage: Optional[Usage] = Usage()
    """Usage object containing metrics of resource usage from generating the response"""
    additional_kwargs: Optional[Dict] = {}
    """Optional dictionary of additional keyword arguments"""


class MCPRequest(BaseModel):
    """
    # MCPRequest
    Represents a request to the MCP API.

    ## Attributes
    - `mcp_servers` (List[MCPServer]): List of MCPServer objects.
    - `user_input` (str): User input string.
    """

    mcp_servers: List[str]
    """List of MCPServer objects"""
    user_input: str
    """User input string"""