import logging
import os
from dotenv import load_dotenv
from langchain_openai import AzureChatOpenAI

"""The API key for the LLMOPS API."""
LLMOPS_API_KEY = os.getenv("LLMOPS_API_KEY")
LOGGING_ENDPOINT = os.getenv("LOGGING_ENDPOINT")

GPT_DEPLOYMENT = os.getenv("AZURE_DEPLOYMENT")
MINI_DEPLOYMENT = os.getenv("AZURE_DEPLOYMENT_MINI") or GPT_DEPLOYMENT

MODEL = GPT_DEPLOYMENT
MINI_MODEL = MINI_DEPLOYMENT

JIRA_API_KEY = os.getenv("JIRA_API_KEY")
JIRA_EMAIL = os.getenv("JIRA_EMAIL")

FRONTEND_VERSION = os.getenv("FRONTEND_VERSION")
VITE_ENV_MODE = (os.getenv("VITE_ENV_MODE") or "development").strip().lower()
VITE_FRONTEND_BASE_URL_DEV = os.getenv("VITE_FRONTEND_BASE_URL_DEV")
VITE_FRONTEND_BASE_URL_PROD = os.getenv("VITE_FRONTEND_BASE_URL_PROD")


def _is_truthy_env(value: str | None) -> bool:
    return str(value or "").strip().lower() in {"1", "true", "yes", "on"}

# Email notifications are generated by the backend, so it must use the same
# environment selection as the frontend build. Keep FRONTEND_BASE_URL only as
# a backward-compatible fallback while deployments move to the VITE_* settings.
FRONTEND_BASE_URL = (
    VITE_FRONTEND_BASE_URL_PROD
    if VITE_ENV_MODE == "production"
    else VITE_FRONTEND_BASE_URL_DEV
) or os.getenv("FRONTEND_BASE_URL")

ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")

KNOWLEDGE_BASE_URL = os.getenv("KNOWLEDGE_BASE_URL")

CHATBOT_KB_BASE_URL = os.getenv("CHATBOT_KB_BASE_URL")

NOTIFICATION_API_URL = os.getenv(
    "NOTIFICATION_API_URL",
    "https://automationplatform.azurewebsites.net/api/mailnotification",
)
NOTIFICATION_SENDER_EMAIL = os.getenv(
    "NOTIFICATION_SENDER_EMAIL",
    "noreply@fridaplatform.online",
)
NOTIFICATION_SENDER_NAME = os.getenv(
    "NOTIFICATION_SENDER_NAME",
    "FridaPlatform",
)
DISABLE_EMAIL_NOTIFICATIONS = _is_truthy_env(
    os.getenv("DISABLE_EMAIL_NOTIFICATIONS")
)

logging.getLogger(__name__).info("Setting up Azure Chat OpenAI clients...")

gpt_client = AzureChatOpenAI(
    azure_deployment=GPT_DEPLOYMENT or MINI_DEPLOYMENT,
    api_version=os.getenv("API_VERSION"),
)

gpt_mini_client = AzureChatOpenAI(
    azure_deployment=MINI_DEPLOYMENT or GPT_DEPLOYMENT,
    api_version=os.getenv("API_VERSION"),
)

# Backward-compatible aliases for existing imports.
gpt40_client = gpt_client
gpt40_mini_client = gpt_mini_client
